"""ML-KEM-512 (Kyber512) parameters matching PQ-Crystals Kyber reference."""

N = 256
Q = 3329
K = 2
ETA1 = 3
ETA2 = 2

SYMBYTES = 32
SSBYTES = 32

POLYBYTES = 384
POLYVECBYTES = K * POLYBYTES

POLYCOMPRESSEDBYTES = 128
POLYVECCOMPRESSEDBYTES = K * 320

INDCPA_MSGBYTES = SYMBYTES
INDCPA_PUBLICKEYBYTES = POLYVECBYTES + SYMBYTES
INDCPA_SECRETKEYBYTES = POLYVECBYTES
INDCPA_BYTES = POLYVECCOMPRESSEDBYTES + POLYCOMPRESSEDBYTES

PUBLICKEYBYTES = INDCPA_PUBLICKEYBYTES
SECRETKEYBYTES = INDCPA_SECRETKEYBYTES + INDCPA_PUBLICKEYBYTES + 2 * SYMBYTES
CIPHERTEXTBYTES = INDCPA_BYTES

XOF_BLOCKBYTES = 168
